name: "Wols-CA MQTT AutomationUploader"
version: "1.0.2"
slug: "wols_ca_uploader"
description: "Uploads automations to HA via MQTT"
startup: "services"
boot: "auto"
arch:
  - amd64
  - aarch64
  - armv7
  - i386
map:
  - config:rw
options: {}
schema: {}
