name: "Wols-CA MQTT AutomationUploader"
version: "1.3.3"
slug: "wols_ca_uploader"
description: "Uploads automations to HA via MQTT"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
options:
  mqtt_broker: "192.168.101.240"
  mqtt_port: 1883
  mqtt_user: "wols-ca-admin"
  mqtt_password: ""
  mqtt_topic: "wols-ca/admin/automation_upload"
schema:
  mqtt_broker: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_password: str?
  mqtt_topic: str
